export const RCharacterArtsArray = [
  "card" ,
  "constellation" ,
  "constellation-1" ,
  "constellation-2" ,
  "constellation-3" ,
  "constellation-4" ,
  "constellation-5" ,
  "constellation-6" ,
  "constellation-shape" ,
  "gacha-card" ,
  "gacha-splash" ,
  "icon" ,
  "icon-big" ,
  "icon-side" ,
  "namecard-background" ,
  "portrait" ,
  "talent-burst" ,
  "talent-na" ,
  "talent-passive-0" ,
  "talent-passive-1" ,
  "talent-passive-2" ,
  "talent-skill" ] as const;

export type RCharacterArtsTypeClass = typeof RCharacterArtsArray;

export enum RCharacterArtsTypeListEnum {
  CARD = "card",
  CONSTELLATION = "constellation",
  CONSTELLATION_1 = "constellation-1",
  CONSTELLATION_2 = "constellation-2",
  CONSTELLATION_3 = "constellation-3",
  CONSTELLATION_4 = "constellation-4",
  CONSTELLATION_5 = "constellation-5",
  CONSTELLATION_6 = "constellation-6",
  CONSTELLATION_SHAPE = "constellation-shape",
  GACHA_CARD = "gacha-card",
  GACHA_SPLASH = "gacha-splash",
  ICON = "icon",
  ICON_BIG = "icon-big",
  NAMECARD_BACKGROUND = "namecard-background",
  PORTAIT = "portrait",
  TALENT_BURST = "talent-burst",
  TALENT_NA = "talent-na",
  TALENT_PASSIVE_0 = "talent-passive-0",
  TALENT_PASSIVE_1 = "talent-passive-1",
  TALENT_PASSIVE_2 = "talent-passive-2",
  TALENT_SKILL = "talent-skill",
};