export type SkillTalentTypeClass = "NORMAL_ATTACK" | "ELEMENTAL_SKILL" | "ELEMENTAL_BURST"

export enum SkillTalentTypeListEnum {
    NORMAL_ATTACK = "NORMAL_ATTACK",
    ELEMENTAL_SKILL = "ELEMENTAL_SKILL",
    ELEMENTAL_BURST = "ELEMENTAL_BURST"
}