export const LCharacterArtsArray = [
  "card" ,
  "constellation" ,
  "constellation1" ,
  "constellation2" ,
  "constellation3" ,
  "constellation4" ,
  "constellation5" ,
  "constellation6" ,
  "constellationShape" ,
  "gachaCard" ,
  "gachaSplash" ,
  "icon" ,
  "iconBig" ,
  "iconSide" ,
  "namecardBackground" ,
  "portrait" ,
  "talentBurst" ,
  "talentNa" ,
  "talentPassive0" ,
  "talentPassive1" ,
  "talentPassive2" ,
  "talentSkill" ] as const

export type LCharacterArtsTypeClass = typeof LCharacterArtsArray;

export enum LCharacterArtsTypeListEnum {
  CARD = "card",
  CONSTELLATION = "constellation",
  CONSTELLATION_1 = "constellation1",
  CONSTELLATION_2 = "constellation2",
  CONSTELLATION_3 = "constellation3",
  CONSTELLATION_4 = "constellation4",
  CONSTELLATION_5 = "constellation5",
  CONSTELLATION_6 = "constellation6",
  CONSTELLATION_SHAPE = "constellationShape",
  GACHA_CARD = "gachaCard",
  GACHA_SPLASH = "gachaSplash",
  ICON = "icon",
  ICON_BIG = "iconBig",
  NAMECARD_BACKGROUND = "namecardBackground",
  PORTAIT = "portrait",
  TALENT_BURST = "talentBurst",
  TALENT_NA = "talentNa",
  TALENT_PASSIVE_0 = "talentPassive0",
  TALENT_PASSIVE_1 = "talentPassive1",
  TALENT_PASSIVE_2 = "talentPassive2",
  TALENT_SKILL = "talentSkill",
}